version: 2
jobs:
  build:
    working_directory: ~/graphql-cli-prepare
    docker:
      - image: circleci/node:latest@sha256:f10f2553f8c475c8cff2c352a45fc0e5c0016db76515aab662bc398e04597436
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release || true